config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :conversations
      resources :messages
      resources :publishes
      resources :users

      root to: "conversations#index"
    end
	get '/register', to: 'users#new' # manually mapping user registration to /register instead of /users/new -> therefore not listed under resources

	resources :users, only: [:show, :create, :edit, :update] #note we don't want an index route to show all users

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	get '/logout', to: 'sessions#destroy'
	

	root 'publishes#index'
	resources :publishes
	resources :users

	resources :conversations, only: [:index, :create] do
	  resources :messages, only: [:index, :create]
	end


  	get 'auth/:provider/callback' , to: 'sessions#create'
  	get 'auth/failure' , to: redirect('/')
  	get 'signout' , to: 'sessions#destroy' , as: 'signout'
  
  	
  	# ----- end of added lines -----
	
end

app/models/publish.rb
class Publish < ApplicationRecord
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "600x600>", thumb: "500x400>" }, :default_url => "https://39lm5827fzpu40ze7s2y2ses-wpengine.netdna-ssl.com/wp-content/uploads/2016/03/dsc4478_25638165340_o-1024x683.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search)
      where("description LIKE ?", "%#{search}%") 
      where("country LIKE ?", "%#{search}%")
  end
end

app/controllers/admin/publishes_controller.rb
module Admin
  class PublishesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Publish.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Publish.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  before_action :set_publish, only: [:show, :edit, :search]
  def index
    @publishes = Publish.all
    if params[:search]
      @publish = Publish.search(params[:search]).order("created_at DESC")
    else
      @publishes = Publish.all.order('created_at DESC')
    end
    @users = User.all
    
  end
  

  def show
    @publish = Publish.find(params[:id])
  end

  def new
    @publish = Publish.new

  end

  def create
    @publish = Publish.new(user_params)
    @publish['user_id'] = current_user.id
    if @publish.save
    	flash[:success] ="Success!"
      redirect_to publish_path(@publish)
    else
      flash[:error] = @publish.errors.full_messages
      redirect_to new_publish_path
    end
  end
  def edit
    
  end

  private
  def set_publish
    @publish = Publish.find(params[:id])
  end

  def user_params
    params.require(:publish).permit(:description, :country, :image)
  end

end

app/views/publishes/_form.html.erb
<%= form_for(@publish) do |f| %>


<div class="form-group">
	<%= f.label :description %>
	<%= f.text_field :description, type: 'text', :class =>"form-control" %>
</div>


<div class="form-group">
	<%= f.label :country %>
	<%= f.text_field :country, type: 'text', :class =>"form-control" %>
</div>

</br>
<div class="form-group">
	<%= f.label :image %>
	<%= f.file_field :image %>
</div>

</br>


</br>
<%= f.button :submit , class: "btn btn-dark" %>
</br>

</div>

<% end %>

app/views/publishes/index.html.erb
<div class="row " style="margin-top: 40px;padding: 20px;" >
    <div class="col  ">
                 <% @publishes.order(created_at: :desc).each do |publish| %>
		              <div class="col-xl " style="margin-left: 50px;">
		                  <div class="card mb-5 p-0">
		                 		
		                      <div class="card-body shadow-lg  ">
		                          <div class="d-flex flex-inline-block">
		                          <%= link_to image_tag(publish.user.avatar.url, class:'img-fluid' ,style:'width: 30px; border-radius: 50%'), user_path(publish.user_id) %> <p><%= publish.user.username %></p>
		                          </br>
		                          </div>
		                          	<div class="flex-inline-block">
		                          		<h6><%= link_to publish.country  %></h6>
		                      		</div>
		                        	<div class="image" >
		                         		<%= image_tag publish.image.url ,style:"width: 950px;" %>
		                         	</div>
		                         </br></br>
		                         	<div
									  class="fb-like"
									  data-share="true"
									  data-width="450"
									  data-show-faces="true">
									</div>
		                         </br>
		                         	<div class="flex-inline-block">
		                          		<h6><%= publish.description %></h6>
		                      		</div>
		                             	<%= link_to "Check ", "/publishes/#{publish.id}", class:'btn btn-dark p-1'%>
		                    			  <!-- Load Facebook SDK for JavaScript -->
  											
		                      </div>

		                  </div>
		              </div>
		              
		          <% end %>
	</div>
					<% if current_user %>
				
		         	<div class="col" style="padding: 60px; overflow: scroll; ">
		         		 <%= form_tag(publishes_path, :method => "get", id: "search-form") do %>
				        <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
				        <%= submit_tag "Search" ,  class:'btn btn-dark p-1' %>
				        <% end %></br>

	      				<div class="card-body shadow-lg " style="position: absolute; " >
	      					<h1 class="d-flex flex-wrap justify-content-center">Direct</h1>
	      					<% if current_user %>
	      					<div class="btn btn-info p-2 pl-3 mr-4 mt-5 border">
	      					 <%= link_to current_user.username , user_path(current_user.id) ,style:"color:black" %>
	      				     </div>
	      					<% end %>
	      				</br></br>
								<ul id="users" class="list-group">
										<% @users.each do |user| %>
								        <li class="list-group-item" data-searchstring="<% user.avatar %><%= user.username %>">
								        	<% if current_user %>
								          <%= link_to user.username, conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post , style:"color:black"%>
								          <% end %>
								        </li>
								     <% end %>
								</ul>
						</div>
	       			</div>
	       			<% end %>
				</div>
				




		<script>
		  window.fbAsyncInit = function() {
		    FB.init({
		      appId      : '242089279811145',
		      xfbml      : true,
		      version    : 'v3.1'
		    });
		    FB.AppEvents.logPageView();
		  };

		  (function(d, s, id){
		     var js, fjs = d.getElementsByTagName(s)[0];
		     if (d.getElementById(id)) {return;}
		     js = d.createElement(s); js.id = id;
		     js.src = "https://connect.facebook.net/en_US/sdk.js";
		     fjs.parentNode.insertBefore(js, fjs);
		   }(document, 'script', 'facebook-jssdk'));
		</script>
</div>	  
       
  

app/views/publishes/more.html.erb
<div class="jumbotron jumbotron-fluid" style='background-color: #e9e8e6'></div>
<div class="container1" style="
    margin-top: -542px;" >
    <div style=" padding: 40px;">
        <h1>Posts</h1>

        <%= form_tag(more_publishes_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
        <%= submit_tag "Search" ,  class:'btn btn-dark p-1' %>
        <% end %>
        
        </br>
        
    <%= link_to 'New Post', new_publish_path , class:'btn btn-dark p-1' %>

  
    </div>
    
    <div class="row shadow-lg p-3 mb-5 bg-white rounded "style="padding:70px;">

          <% @publishes.each do |publish| %>
              <div class="col-4">
                  <div class="card mb-5">
                 <iframe width="auto" height="auto" src="https://www.youtube.com/embed/<%= challenge.after_video %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>			
                      <div class="card-body">
                      
                         
                          <div class="d-flex flex-inline-block">
                          <%= link_to image_tag(publish.user.avatar.url, class:'img-fluid' ,style:'width: 30px; border-radius: 50%'), user_path(publish.user_id) %> <p><%= publish.user.username %></p>
                          </br>
                          </div>
                             <%= link_to "Check ", "/publishes/#{publish.id}", class:'btn btn-dark p-1'%>
                        
                      </div>
                  </div>
              </div>
              
          <% end %>
         
      </div>


  <br><hr>
  
       
  

app/views/publishes/new.html.erb
<div class="jumbotron jumbotron-fluid" style='background-color: #61c0bf ; height: 100%; '>

    <div class = "container" style="width: 700px; margin-top: 80px;" >
    	<div class="card border shadow-lg">
    	<h5 class="card-header text-dark" style="background-color: #C8C8C8;">New Publish</h5>
    		<div class="p-3">
        <p style="color:#8b8989"></p>

        <%= render partial: '/publishes/form', object: @publish %>
        </div>
        <div class="form-actions my-3 d-flex justify-content-end">

                <%= link_to 'Back', publishes_path ,class: "btn btn-dark" %>
        </div>
    </div>
</div>

</div>

app/views/publishes/show.html.erb
<div class="shadow-lg p-0 mb-5 bg-white rounded " style=" margin-left: 100px; width: 400px;">
	<div class="panel panel-default  ">
		<div class="panel-body">
			<h5 class="card-header text-dark mb-3" style="background-color: #C8C8C8;"><%= link_to image_tag(@publish.user.avatar.url, class:'img-fluid' ,style:'height:40px; border-radius: 50%'), user_path(@publish.user_id) %><%= @publish.user.username %></h5>


				<!-- Main Info -->
				<div class="row p-3">
					<div class="text-centre row-space-1">
						<span style="font-weight: bold;"></span><%= @publish.country %>

					</div>
					<div class="col-md-8">

						<div class="row">

							<div class="col-md-3 text-center">

								<div class="image">
			                         	<%= image_tag @publish.image.url ,style:"width: 950px;" %>
			                    </div>
								
							</div>
							

					    </div>
						<div class="col-md-3" >
								
							
								
						</div>
					</div>
				</div>
	                 <h6><%= @publish.description %></h6>
		</div>
	</div>
				
</div>