config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :conversations
      resources :messages
      resources :publishes
      resources :users

      root to: "conversations#index"
    end
	get '/register', to: 'users#new' # manually mapping user registration to /register instead of /users/new -> therefore not listed under resources

	resources :users, only: [:show, :create, :edit, :update] #note we don't want an index route to show all users

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	get '/logout', to: 'sessions#destroy'
	

	root 'publishes#index'
	resources :publishes
	resources :users

	resources :conversations, only: [:index, :create] do
	  resources :messages, only: [:index, :create]
	end


  	get 'auth/:provider/callback' , to: 'sessions#create'
  	get 'auth/failure' , to: redirect('/')
  	get 'signout' , to: 'sessions#destroy' , as: 'signout'
  
  	
  	# ----- end of added lines -----
	
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
	<p class ="notice"><%= notice %></p>
	<p class ="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
   
  

  <body>
   <nav class="navbar navbar-expand-lg navbar-light bg-blue">
  <a class="navbar-brand" style="font-family: 'Merienda', cursive;" href="/">POSTGRAM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link " href="/publishes/new">New Post <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
      <a class="nav-link " href="/admin">Admin <span class="sr-only">(current)</span></a>
    </li>
      <li class="nav-item">
       
      </li>
        <div class="nav-link">
         <% if current_user %>
         <%= link_to 'Sign out', logout_path, :class => style="color: #3b3a39;" %>
        </div>
         <% else %>
        <div class="nav-link">
          <%= link_to 'Sign in', login_path, :class => style="color: #3b3a39;" %>
        </div>
        <div class="nav-link">
          <%= link_to 'Sign up', register_path, :class => style="color: #3b3a39;" %>
        <% end %>
      </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-1">
      
     

    </form>
  </div>
</nav>
<% if flash.any? %>
  <p class ="notice"><%= notice %></p>
  <p class ="alert"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>